name: Wisecow CI/CD Pipeline

# Run this workflow whenever code is pushed to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ganeshreddy170 }}
          password: ${{ secrets.dckr_pat_CminT-WOl7kfYJE75tBxD6qHBjE }}

      # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ganeshreddy170 }}/ganesh17:tagname .
          docker push ${{ secrets.ganeshreddy170 }}/ganesh17:tagname

  deploy:
    name: Deploy to Kubernetes (optional)
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy updated Wisecow image
        run: |
          kubectl set image deployment/wisecow-deployment wisecow-container=${{ secrets.ganeshreddy170 }}/ganesh17:tagname
          kubectl rollout status deployment/wisecow-deployment
